version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  custodian-service:
    build: ./custodian-service
    container_name: custodian-service
    ports:
      - "8010:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3002:3002"
    environment:
      - VITE_API_URL=http://localhost:8010
    depends_on:
      - custodian-service

volumes:
  mongo_data:
