services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  custodian-service:
    build: ./custodian-service
    container_name: custodian-service
    ports:
      - "8010:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "8020:8000"
    environment:
      - CUSTODIAN_SERVICE_URL=http://custodian-service:8000/api
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USE_SSL=false
    depends_on:
      - custodian-service
      - opensearch

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3002:3002"
    environment:
      - VITE_API_URL=http://localhost:8010/api
      - VITE_SEARCH_API_URL=http://localhost:8020/graphql
    depends_on:
      - custodian-service
      - search-service

volumes:
  mongo_data:
  opensearch_data:
