apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  namespace: financial-advisory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
# For local development with Docker Desktop Kubernetes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/opensearch"
  persistentVolumeReclaimPolicy: Retain