apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: financial-advisory
  labels:
    app: opensearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9600
    targetPort: 9600
    protocol: TCP
    name: transport
  selector:
    app: opensearch
  type: ClusterIP