apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: financial-advisory
data:
  api_url: "http://financial-advisory.local/api"
  environment: "production"
  feature_flags: |
    {
      "enableMicroFrontends": false,
      "enableDarkMode": true,
      "enableNotifications": true,
      "enableExperimentalFeatures": false
    }