apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: financial-advisory
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: frontend
  type: ClusterIP