apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: financial-advisory
spec:
  selector:
    matchLabels:
      app: search-service
  replicas: 2
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: financial-advisory/search-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: CUSTODIAN_SERVICE_URL
          value: "http://custodian-service:8000/api"
        - name: OPENSEARCH_HOST
          value: "opensearch"
        - name: OPENSEARCH_PORT
          value: "9200"
        - name: OPENSEARCH_USE_SSL
          value: "false"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: search-service-config
              key: log_level
              optional: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5