apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: financial-advisory
  labels:
    app: search-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: search-service
  type: ClusterIP